import Link from 'next/link';
import GrowthAuditForm from '@/components/growth/GrowthAuditForm';
import { growthMetadata, SITE_URL } from '@/app/lib/growth-content';

export const metadata = growthMetadata('Book a Growth Systems Audit', 'Identify the highest-impact opportunity across discoverability, conversion, automation, company knowledge, private AI, and reporting.', '/book');

export default function BookPage() {
  const schema = { '@context': 'https://schema.org', '@type': 'Service', name: 'Growth Systems Audit', provider: { '@type': 'Organization', name: 'OfRoot', url: SITE_URL }, areaServed: 'US', description: 'A focused review of discoverability, lead conversion, automation, internal knowledge, private AI, and reporting opportunities.' };
  return <main id="main-content" className="bg-[#f7f6f2] px-6 py-16 text-slate-950 sm:px-8 sm:py-24"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="mx-auto max-w-6xl"><nav aria-label="Breadcrumb" className="mb-10 text-sm text-slate-500"><Link href="/">Home</Link> / <span className="text-slate-950">Book</span></nav><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="mb-4 text-sm font-bold uppercase tracking-[.18em] text-[#B55B00]">Growth Systems Audit</p><h1 className="text-balance text-4xl font-black sm:text-6xl">Find the bottleneck worth fixing first.</h1><p className="mx-0 mt-6 text-lg text-slate-600">The audit helps identify the highest-impact opportunity across discoverability, lead conversion, automation, internal knowledge, private AI, and reporting.</p><div className="mt-9 space-y-5 border-l-2 border-[#FF9312] pl-5">{[['What enters', 'Your current goals, systems, bottleneck, and desired outcome.'], ['What we examine', 'The path from visibility to conversion to day-to-day execution.'], ['What leaves', 'A focused recommendation for the next useful system change.']].map(([title, body]) => <div key={title}><h2 className="text-base font-bold">{title}</h2><p className="mx-0 mt-1 text-sm text-slate-600">{body}</p></div>)}</div><p className="mx-0 mt-9 text-sm text-slate-500">Already booked through the existing consulting flow? <Link href="/consulting/book" className="font-semibold text-[#8F4700] hover:underline">Open the calendar page.</Link></p></div><GrowthAuditForm /></div></div></main>;
}
