import type { Metadata } from 'next';
import Link from 'next/link';
import { SITE } from '@/app/config/site';

export const metadata: Metadata = { title: 'OfRoot Technology Editorial Team', description: 'How the OfRoot Technology Editorial Team creates, sources, reviews, and maintains practical guidance about AI discoverability, automation, and company AI.', alternates: { canonical: '/authors/ofroot-technology' } };

export default function OfRootAuthorPage() {
  const profile = { '@context': 'https://schema.org', '@type': 'ProfilePage', mainEntity: { '@type': 'Organization', name: 'OfRoot Technology Editorial Team', url: `${SITE.url}/authors/ofroot-technology`, parentOrganization: { '@type': 'Organization', name: SITE.name, url: SITE.url }, knowsAbout: ['AI discoverability', 'workflow automation', 'AI agent integration', 'private company AI'] } };
  return <main id="main-content" className="bg-[#f7f6f2] text-slate-950"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(profile) }} /><div className="mx-auto max-w-4xl px-6 py-16 sm:px-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#9A4A00]">Author profile</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">OfRoot Technology Editorial Team</h1><p className="mt-6 text-xl leading-8 text-slate-600">OfRoot’s practical guidance is prepared by the technology team responsible for designing growth, automation, integration, and company-AI systems. We use an organization byline until a named contributor has reviewed and approved publication under their own profile.</p><div className="mt-12 grid gap-5 sm:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-black">What we cover</h2><p className="mt-3 leading-7 text-slate-600">AI discoverability, technical search foundations, workflow automation, CRM and API integration, private company knowledge systems, AI-agent controls, evaluation, and observability.</p></section><section className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-black">How we publish</h2><p className="mt-3 leading-7 text-slate-600">We separate documented evidence from opinion, link to primary sources where practical, disclose limitations, avoid invented outcomes, and record substantive update dates.</p></section></div><div className="mt-10 flex flex-wrap gap-4"><Link href="/about/editorial-standards" className="font-bold text-[#8F4700] underline">Read our editorial standards</Link><Link href="/insights" className="font-bold text-[#8F4700] underline">Browse the insight library</Link><a href="mailto:communications@ofroot.technology" className="font-bold text-[#8F4700] underline">Request a correction</a></div></div></main>;
}
