import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Calculator, Check, Network, ShieldCheck, TrendingUp } from 'lucide-react';
import JsonLd from '@/components/seo/JsonLd';
import { TrackedLink, TrackedPageView } from '@/components/growth/Analytics';
import { CANONICAL_SITE_URL, SITE } from '@/app/config/site';
import { AI_PROCESS_GUIDE } from '@/app/lib/ai-process-guide';

export const metadata: Metadata = {
  title: AI_PROCESS_GUIDE.title,
  description: AI_PROCESS_GUIDE.description,
  alternates: { canonical: AI_PROCESS_GUIDE.href },
  openGraph: { title: AI_PROCESS_GUIDE.title, description: AI_PROCESS_GUIDE.description, url: `${CANONICAL_SITE_URL}${AI_PROCESS_GUIDE.href}`, type: 'article', publishedTime: `${AI_PROCESS_GUIDE.publishedAt}T08:00:00-05:00`, authors: ['OfRoot Technology'] },
  twitter: { card: 'summary_large_image', title: AI_PROCESS_GUIDE.title, description: AI_PROCESS_GUIDE.description },
};

const scoringFactors = [
  ['Annual value', 'How much approved cost, delay, rework, or lost capacity could change?'],
  ['Frequency', 'How often does the workflow run, and how predictable are its inputs?'],
  ['Feasibility', 'Are the data, systems, rules, and owners clear enough to implement safely?'],
  ['Risk', 'What happens when the system is wrong, unavailable, or used outside its intended boundary?'],
  ['Adoption', 'Will the people doing the work use the new process consistently?'],
] as const;

const faqs = [
  { question: 'Should we automate the most annoying task first?', answer: 'Not automatically. Frustration is useful evidence, but frequency, cost, risk, feasibility, and adoption determine whether the task is a strong first project.' },
  { question: 'Does every manual process need AI?', answer: 'No. A clear rule, better form, direct integration, or removed approval step may solve the problem more reliably than an AI model.' },
  { question: 'What if we do not have clean time data?', answer: 'Start with a bounded observation period. Record volume, handling time, delay, rework, and exceptions for a representative sample, then label every estimate as an assumption until it is approved.' },
  { question: 'How do we prove the automation worked?', answer: 'Agree on a baseline before launch, then measure the same units after launch: time per case, throughput, delay, error rate, adoption, and recovery effort.' },
] as const;

export default function AiProcessGuidePage() {
  const article = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: AI_PROCESS_GUIDE.title, description: AI_PROCESS_GUIDE.description, datePublished: AI_PROCESS_GUIDE.publishedAt, dateModified: AI_PROCESS_GUIDE.publishedAt, author: { '@type': 'Organization', name: 'OfRoot Technology', url: SITE.url }, publisher: { '@type': 'Organization', name: SITE.name, url: SITE.url, logo: SITE.logo }, mainEntityOfPage: `${CANONICAL_SITE_URL}${AI_PROCESS_GUIDE.href}` };
  const breadcrumb = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: CANONICAL_SITE_URL }, { '@type': 'ListItem', position: 2, name: 'Blog', item: `${CANONICAL_SITE_URL}/blog` }, { '@type': 'ListItem', position: 3, name: AI_PROCESS_GUIDE.title, item: `${CANONICAL_SITE_URL}${AI_PROCESS_GUIDE.href}` }] };
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
  const primary = 'inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#FF9312] px-6 py-3 font-extrabold text-slate-950 shadow-[0_12px_30px_rgba(255,147,18,.2)] transition hover:-translate-y-0.5 hover:bg-[#ffad42] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#37FFE0] focus-visible:ring-offset-2 focus-visible:ring-offset-[#071225] motion-reduce:transform-none';

  return (
    <main id="main-content" className="bg-[#f7f6f2] text-slate-950">
      <JsonLd data={[article, breadcrumb, faqSchema]} />
      <TrackedPageView event="ai_process_article_viewed" label={AI_PROCESS_GUIDE.slug} />
      <article>
        <header className="relative isolate overflow-hidden bg-[#071225] px-6 py-16 text-white sm:px-8 sm:py-24">
          <div className="absolute inset-0 -z-10 opacity-70 [background:radial-gradient(circle_at_82%_16%,rgba(55,255,224,.14),transparent_34%),radial-gradient(circle_at_12%_88%,rgba(255,147,18,.16),transparent_30%)]" />
          <div className="mx-auto max-w-5xl"><nav aria-label="Breadcrumb" className="mb-10 text-sm text-slate-400"><Link href="/" className="hover:text-white">Home</Link><span aria-hidden="true"> / </span><Link href="/blog" className="hover:text-white">Blog</Link><span aria-hidden="true"> / </span><span className="text-white">AI Process</span></nav><p className="mb-5 text-sm font-bold uppercase tracking-[.2em] text-[#FFC46B]">{AI_PROCESS_GUIDE.eyebrow}</p><h1 className="max-w-5xl text-balance text-5xl font-black leading-[.98] text-white sm:text-7xl">{AI_PROCESS_GUIDE.title}</h1><p className="mx-0 mt-7 max-w-3xl text-lg text-slate-200 sm:text-xl">{AI_PROCESS_GUIDE.description}</p><div className="mt-8 flex flex-wrap gap-4 text-sm text-slate-400"><span>By OfRoot Technology</span><span>{AI_PROCESS_GUIDE.displayDate}</span><span>{AI_PROCESS_GUIDE.readingTime}</span></div></div>
        </header>

        <div className="mx-auto grid max-w-6xl gap-12 px-6 py-16 sm:px-8 lg:grid-cols-[220px_1fr] lg:py-20">
          <aside><nav aria-label="Table of contents" className="sticky top-24 rounded-2xl border border-slate-200 bg-white p-5"><p className="mb-3 font-bold">On this page</p><ol className="space-y-2 text-sm text-slate-600"><li><a href="#direct-answer" className="hover:text-[#8F4700]">Direct answer</a></li><li><a href="#map" className="hover:text-[#8F4700]">Map the work</a></li><li><a href="#cost" className="hover:text-[#8F4700]">Calculate cost</a></li><li><a href="#score" className="hover:text-[#8F4700]">Score opportunities</a></li><li><a href="#build" className="hover:text-[#8F4700]">Choose a safe build</a></li><li><a href="#measure" className="hover:text-[#8F4700]">Measure the result</a></li><li><a href="#faq" className="hover:text-[#8F4700]">FAQ</a></li></ol></nav></aside>
          <div className="max-w-3xl">
            <section id="direct-answer" className="scroll-mt-24 rounded-3xl border border-[#FF9312]/30 bg-[#fff8ee] p-7 sm:p-9"><p className="mb-3 text-xs font-bold uppercase tracking-[.15em] text-[#9A4A00]">Direct answer</p><p className="mx-0 text-xl font-semibold leading-relaxed sm:text-2xl">The best first automation is usually a frequent, costly, rules-visible workflow with reliable inputs, a clear owner, and a measurable output. Find it by mapping the real process, calculating the current cost, scoring value against risk and feasibility, then testing the smallest reversible change.</p><p className="mx-0 mt-5 text-slate-600">That is the core logic behind an <Link href="/ai-process" className="font-bold text-[#8F4700] underline decoration-[#FF9312]/40 underline-offset-4">AI Process Audit</Link>.</p></section>

            <section id="map" className="scroll-mt-24 border-b border-slate-200 py-12"><Network className="h-7 w-7 text-[#9A4D00]" /><p className="mb-3 mt-6 text-xs font-bold text-[#B55B00]">01</p><h2 className="text-balance text-3xl font-black sm:text-4xl">Map the work people actually do.</h2><p className="mx-0 mt-5 text-lg text-slate-700">Job titles and software lists rarely reveal the expensive part. Follow one unit of work from trigger to outcome. Ask what enters, what changes, who decides, where it waits, and what happens when reality does not match the happy path.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{[['Inputs', 'Requests, files, messages, records, or events that begin the work.'], ['Processing', 'Rules, judgments, transformations, approvals, and repeated actions.'], ['Outputs', 'The completed record, response, document, handoff, or customer result.'], ['Dependencies', 'People, permissions, systems, data quality, and timing assumptions.'], ['Failure points', 'Exceptions, rework, missing context, silent errors, and recovery steps.']].map(([title, body]) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-black">{title}</h3><p className="mx-0 mt-2 text-sm text-slate-600">{body}</p></div>)}</div><p className="mx-0 mt-7 text-slate-700">Look for copied data, repeated document assembly, delayed routing, manual status checks, duplicate approvals, and reports rebuilt from the same sources. The adjacent <Link href="/automations" className="font-bold text-[#8F4700] hover:underline">automation services overview</Link> shows common implementation patterns, but the process map should come first.</p></section>

            <section id="cost" className="scroll-mt-24 border-b border-slate-200 py-12"><Calculator className="h-7 w-7 text-[#9A4D00]" /><p className="mb-3 mt-6 text-xs font-bold text-[#B55B00]">02</p><h2 className="text-balance text-3xl font-black sm:text-4xl">Calculate the cost of the current process.</h2><p className="mx-0 mt-5 text-lg text-slate-700">Manual time is the easiest cost to see, but it is not the whole cost. Include the time spent doing the work, waiting for the work, correcting the work, and recovering when a handoff fails.</p><div className="mt-8 rounded-3xl bg-[#071225] p-7 text-white"><p className="text-sm font-bold uppercase tracking-[.15em] text-[#FFC46B]">A simple starting model</p><p className="mt-5 text-2xl font-black text-white">Annual process cost = labor + delay + rework + error exposure</p><ul className="mt-6 space-y-3 text-sm text-slate-300"><li>Labor: handling hours × loaded hourly cost × annual volume</li><li>Delay: approved value lost while work waits</li><li>Rework: repeated handling caused by incomplete or incorrect inputs</li><li>Error exposure: expected cost of mistakes, weighted by likelihood</li></ul></div><div className="mt-7 rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="font-bold text-amber-950">Illustrative example — not a customer result</p><p className="mx-0 mt-2 text-sm text-amber-900">Ten reporting hours per week at a $50 loaded hourly cost equals $26,000 in annual manual labor. If evidence suggests 70% of that work can be removed safely, the estimated opportunity is $18,200 before implementation cost, adoption, and operating risk.</p></div></section>

            <section id="score" className="scroll-mt-24 border-b border-slate-200 py-12"><TrendingUp className="h-7 w-7 text-[#9A4D00]" /><p className="mb-3 mt-6 text-xs font-bold text-[#B55B00]">03</p><h2 className="text-balance text-3xl font-black sm:text-4xl">Score the opportunity, not the excitement.</h2><p className="mx-0 mt-5 text-lg text-slate-700">A promising demo can hide an expensive operating contract. Rank each opportunity with the same factors so the loudest request does not automatically become the roadmap.</p><dl className="mt-8 divide-y divide-slate-200 border-y border-slate-200">{scoringFactors.map(([term, definition]) => <div key={term} className="grid gap-2 py-5 sm:grid-cols-[10rem_1fr]"><dt className="font-black">{term}</dt><dd className="text-slate-600">{definition}</dd></div>)}</dl><p className="mx-0 mt-7 text-slate-700">The highest-value project is not always first. A smaller workflow with cleaner inputs and lower failure cost may produce faster evidence and a better foundation for expansion. OfRoot’s <Link href="/services/automation-systems" className="font-bold text-[#8F4700] hover:underline">Automation Systems</Link> work uses this operating view rather than treating every connection as an isolated integration.</p></section>

            <section id="build" className="scroll-mt-24 border-b border-slate-200 py-12"><ShieldCheck className="h-7 w-7 text-[#9A4D00]" /><p className="mb-3 mt-6 text-xs font-bold text-[#B55B00]">04</p><h2 className="text-balance text-3xl font-black sm:text-4xl">Choose the smallest safe build.</h2><p className="mx-0 mt-5 text-lg text-slate-700">Start with one trigger, one accountable owner, one observable output, and a clear recovery path. A useful first release may be a direct integration, a deterministic rule, a human-approved AI draft, or the removal of an unnecessary step.</p><ul className="mt-7 space-y-3">{['Define what the system may and may not do.', 'Keep sensitive or costly actions behind human approval.', 'Log inputs, decisions, outputs, and failures clearly.', 'Test normal cases, bad inputs, duplicates, timeouts, and recovery.', 'Preserve a manual fallback and an explicit rollback path.'].map((item) => <li key={item} className="flex gap-3 text-slate-700"><Check className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700" />{item}</li>)}</ul><p className="mx-0 mt-7 text-slate-700">AI is appropriate when the workflow contains language, classification, extraction, or judgment that can be bounded and reviewed. It is unnecessary when a stable rule or ordinary integration solves the problem more reliably.</p></section>

            <section id="measure" className="scroll-mt-24 border-b border-slate-200 py-12"><TrendingUp className="h-7 w-7 text-[#9A4D00]" /><p className="mb-3 mt-6 text-xs font-bold text-[#B55B00]">05</p><h2 className="text-balance text-3xl font-black sm:text-4xl">Measure the same process after launch.</h2><p className="mx-0 mt-5 text-lg text-slate-700">Agree on the baseline before implementation. After launch, compare the same units: handling time, throughput, wait time, error rate, rework, adoption, and recovery effort. Savings are realized only when the new process is used and the old work actually disappears.</p><div className="mt-8 rounded-3xl border border-slate-200 bg-white p-7"><h3 className="text-xl font-black">A credible result has four parts.</h3><ol className="mt-5 space-y-3 text-slate-700"><li><strong>Baseline:</strong> the approved current-state measurement.</li><li><strong>Change:</strong> the exact workflow and release boundary.</li><li><strong>Observation window:</strong> when and how the new process was measured.</li><li><strong>Result:</strong> the difference, including adoption, exceptions, and operating cost.</li></ol></div><p className="mx-0 mt-7 text-slate-700">If the result is weak, fix the process before expanding the platform. If the result is strong, the next opportunity should go through the same evidence path.</p></section>

            <section id="faq" className="scroll-mt-24 py-12"><h2 className="text-3xl font-black sm:text-4xl">Frequently asked questions</h2><div className="mt-7 space-y-4">{faqs.map((item) => <details key={item.question} className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-black">{item.question}</summary><p className="mx-0 mt-3 text-slate-600">{item.answer}</p></details>)}</div></section>

            <section className="rounded-3xl bg-[#071225] p-7 text-white sm:p-9"><p className="text-sm font-bold uppercase tracking-[.15em] text-[#FFC46B]">Turn the method into a roadmap</p><h2 className="mt-4 text-balance text-3xl font-black text-white">Find the process worth changing first.</h2><p className="mx-0 mt-4 text-slate-300">The AI Process Audit maps the work, makes cost assumptions visible, ranks opportunities, and defines the smallest practical implementation plan.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><TrackedLink href="/book?focus=ai-process-audit&source=ai-process-article" source="ai-process-article:final" event="ai_process_article_cta_clicked" className={primary}>Book an AI Process Audit<ArrowRight className="h-4 w-4" /></TrackedLink><Link href="/ai-process" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/25 px-6 py-3 font-bold text-white hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#37FFE0]">See the full process</Link></div></section>
          </div>
        </div>
      </article>
    </main>
  );
}
